Refactoring of enki
SiemaApplications/enki pull request #19
Opened 2023-09-11 16:08 UTC by pfayolle

Reworked sp_dev sp_id sp_net sp_topic with clear separation
between the classes.
Added callbacks and a UI protocol class to separate the
display to the user from the core of the app.
Moved the shell interface to a class that follows that protocol
and is not in the main file anymore.
Removed the logger commands.
Added a pylint.rc file for linting and made the style fixes needed.
The code now has a 10.0 score in pylint.

2023-09-12 07:04 UTC, nvincent-vossloh reviewed
In a future PR we should move all strings to f-strings, today it is a mixup of multiple styles.

I think you should add a github workflow to check pylint codestyle, and make it a gate for PR merging.

Is this code compatible with `vog-zephyr-nodes` (updating enki repository reference in the manifest breaks tests/scripts or not) ?

2023-09-12 07:04 UTC, nvincent-vossloh commented on sp_logger.py
Does this mean that the logging function is gone ?
Ideally a logging function will be added in automatic tests to log the sparkplug exchanges for debug purposes.

2023-09-12 07:48 UTC, pfayolle commented on mqtt_if.py
> +    def on_connect(client, userdata, _flags, ret):
The argument is not used in the function, which generates a warning in pylint. The prefix solves this.

2023-09-12 07:49 UTC, pfayolle commented
> I think you should add a github workflow to check pylint codestyle, and make it a gate for PR merging.

I'll look into it

2023-09-13 08:43 UTC, nvincent-vossloh requested changes

2023-09-13 08:43 UTC, nvincent-vossloh commented on .github/workflows/compliance.yml
> +name: Build Docker Image Enki
Could you rename it :wink:

2023-09-13 08:43 UTC, nvincent-vossloh commented on .github/workflows/compliance.yml
> +	  pip install pylint
It looks like you have a weird char here.

2023-09-13 08:43 UTC, nvincent-vossloh commented on .github/workflows/compliance.yml
> +      - name: VOG pylintrc
rename

2023-09-13 08:43 UTC, nvincent-vossloh commented on .github/workflows/compliance.yml
> +          fi
I see you took inspiration from vog-zephyr-nodes. The idea here was to avoid linting the full codebase because individual files would pass but linting everything would fail (copy-paste).
I think you can (and should) lint everything.

2023-09-13 10:15 UTC, pfayolle commented on .github/workflows/compliance.yml
> +	  pip install pylint
Fixed

2023-09-13 10:15 UTC, pfayolle commented on .github/workflows/compliance.yml
> +      - name: VOG pylintrc
Fixed

2023-09-13 10:27 UTC, pfayolle commented on .github/workflows/compliance.yml
> +          fi
Done

2023-09-13 10:35 UTC, nvincent-vossloh approved these changes

2023-09-13 10:37 UTC, pfayolle commented on sp_logger.py
I removed it for now. I'll reintroduce it, with an interface more in line with other commands, when needed

2023-09-13 10:42 UTC, merged